export enum InterventionTriggerType {
  TIMER_ELAPSED = "TIMER_ELAPSED",
  HIGH_LOAD_DETECTED = "HIGH_LOAD_DETECTED",
  USER_REQUESTED = "USER_REQUESTED"
}

export enum StrategyImpact {
  IMPROVED_FLOW = "IMPROVED_FLOW",
  STABILIZED = "STABILIZED",
  NO_CHANGE = "NO_CHANGE",
  INCREASED_OVERWHELM = "INCREASED_OVERWHELM",
  DISMISSED = "DISMISSED"
}